version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:17"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    groups:
      python-dependencies:
        patterns:
          - "*"
